name:              HospitalRun
highlighter:       pygments
description:       "Open source software for developing world hospitals."
url: "http://hospitalrun.io"
permalink:         /blog/:year/:month/:title
exclude:           ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
sass:
sass_dir:        _sass